# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3
  NewCops: enable
  SuggestExtensions: false
plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/FileName:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 50
Style/ConditionalAssignment:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 60
Metrics/ClassLength:
  Max: 160
