assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install --no-color
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" random-port.gemspec
    git add random-port.gemspec
    git commit -m "Version set to ${tag}"
    gem build random-port.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
deploy:
  script: |-
    echo Nothing to deploy
    exit -1
