docker:
  image: yegor256/rultor-image:1.19.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  pre: false
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" random-port.gemspec
    git add random-port.gemspec
    git commit -m "Version set to ${tag}"
    gem build random-port.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
